-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 5bf6c09bfa1297d3692cadd621ef95f1284e33c0
    hooks:
    -   id: trailing-whitespace
        files: \.(js|json|rb|md|py|sh|txt|yaml|yml)$
    -   id: check-yaml
    -   id: check-case-conflict
    -   id: check-json
    -   id: end-of-file-fixer
-   repo: https://github.com/willthames/ansible-lint.git
    sha: v3.4.12
    hooks:
    -   id: ansible-lint
        files: \.(yaml|yml)$
        args:
        - --exclude=.travis.yml
