---
- name: Include OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "vars-{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
    - "vars-{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "vars-family-{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "vars-family-{{ ansible_os_family | lower }}.yml"

- name: Update apt cache
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: (ansible_os_family | lower) == 'debian'

- name: Install ServerSpec Test Dependencies
  become: true
  package:
    name: "{{ serverspec_test_dependencies }}"
    state: present
